### ISSUE TITLE
Were you able to get the ESP32 S2 to run the control surface library?

### ISSUE THREAD

**Issue by fml45678** [blekenbleu/TinyMIDIUSB#1]
Hey, sorry if you explained this already in your documentation (If you did I did not understand), but were you able to use the control surface library with the ESP32-S2. I have been trying to get it to work but have been unsuccessful so far.

Thanks for your help!

**Comment by blekenbleu** [comment]
No.
At the time, ESP32 library hard-coded USB end points, and Espressif rejected an issue to fix the MIDI endpoint.
I did hack an ESP32-S2 MIDI USB implementation, but my application wanted a composite USB device,
and I did not get MIDI working in an ESP32-S2 composite device.
 https://github.com/blekenbleu/composite_sketches

 ESP32-S2 has USB endpoint limitations that were presumably to be fixed in ESP32-S3
 https://blekenbleu.github.io/ESP32/tinyusb.htm
 
 Meanwhile, Espressif appeared more interested in supporting ESP32-C3 than S3.
 I experimented with MIDI over Wi-Fi, but at the time failed to identify or hack a robust open source implementation.
 https://github.com/blekenbleu/composite_sketches 

To start with something reportedly already working, consider this:
https://github.com/mexbeb/esp32-midi-footswitch/releases

... but these guys seemed to make some progress:
https://github.com/tttapa/Control-Surface/issues/900

**Comment by Gershy13** [comment]
Hello, I managed to get it working, see my post here:
https://github.com/tttapa/Control-Surface/issues/900#issuecomment-1709078503

**Comment by fml45678** [comment]
Thanks so much for the help! I will keep working on it and let you know if I figure anything out. Thanks for the workaround suggestion.
